"""empty message

Revision ID: 0d67dcb394ef
Revises: fa0e1efafef5
Create Date: 2016-09-03 08:53:36.419806

"""

# revision identifiers, used by Alembic.
revision = '0d67dcb394ef'
down_revision = 'fa0e1efafef5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'name')
    ### end Alembic commands ###
