"""empty message

Revision ID: ba1889e5a95a
Revises: 0d67dcb394ef
Create Date: 2016-09-04 23:15:10.143839

"""

# revision identifiers, used by Alembic.
revision = 'ba1889e5a95a'
down_revision = '0d67dcb394ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_participations', sa.Column('portions', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_participations', 'portions')
    ### end Alembic commands ###
